baseURL = ""
languageCode = "en-us"
title = "Example jx Blog"
theme = "ananke"
DefaultContentLanguage = "en"

[author]
  name = "jxtsai"
  homepage = "https://jxtsai.info/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.tw]
    contentDir = "content/tw"
    languageName = "Chinese"
    weight = 1

[params]
disqus = "jx-blog" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://about.me/jxtsai"
